In [2]:
try:
    import numpy as np
except ImportError:
    print ("numpy is not installed")

In [3]:
print (np.__version__)

1.18.5


In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[0.2,0.5,0.7],[2.3,5.6,3.7]])

In [9]:
print(b)

[[0.2 0.5 0.7]
 [2.3 5.6 3.7]]


In [10]:
a.ndim

1

In [11]:
b.ndim

2

In [12]:
a.shape


(3,)

In [13]:
b.shape #two rows three coloums

(2, 3)

In [14]:
a.dtype

dtype('int32')

In [15]:
a = np.array([1,2,3],dtype='int32')

In [16]:
a.itemsize


4

In [17]:
a = np.array([1,2,3],dtype='int16')

In [18]:
a.itemsize

2

In [19]:
a.nbytes

6

# Accesing Data

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [21]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
#get a specific element[r,c]
a[1,5]

13

In [23]:
#get a specific row
a[0,:] #first row,all

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# [row, startindex:stopindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [25]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
try:
    import tensorflow as tf
except ImportError:
    print ("tf is not installed")

In [27]:
filedata = np.genfromtxt('data.txt', delimiter=',')

In [28]:
print (filedata)

[[12. 13. 17. 22. 34. 33. 33. 22.]
 [72. 33. 46. 33. 45. 23. 45. 65.]]


In [29]:
filedata > 50

array([[False, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False,  True]])

In [30]:
filedata[filedata > 50]

array([72., 65.])